### ISSUE TITLE
Shaders treat better snow as a part of the plant

### ISSUE THREAD

**Issue by JumperREDACTED** [LambdAurora/LambdaBetterGrass#27] opened 2021-09-18 08:00 UTC
Using Iris for shaders. https://modrinth.com/mod/iris

The snow bobs and weaves along with the foliage and reflects light the way foliage does, rather than the way snow does.

![2021-09-18_09 58 00](https://user-images.githubusercontent.com/83337894/133881414-f49b6d40-41ce-489f-83c9-fda0f45c5544.png)

Not sure if this is fixable, but it would be cool if it would be.

**Comment by yurisuika** [comment] 2021-12-04 14:50
I can confirm this on 1.18 with either Iris+Sodium or Canvas Renderer. OptiFine's BetterSnow must apply its models in a different way as it is compatible with its shaders.

**Comment by LambdAurora** [comment] 2021-12-29 11:14
This is a duplicate of #9.

**Closed as completed by LambdAurora** 2021-12-29 11:14 UTC
Labels: duplicate
