### ISSUE TITLE
[Bug] With Better Snow enabled and shaders (Iris) the "Better Snow animates together with the plant

### ISSUE THREAD

**Issue by RaptaG** [LambdAurora/LambdaBetterGrass#42] opened 2022-02-18 12:26 UTC
![2022-02-18_14 22 34](https://user-images.githubusercontent.com/77157639/154682670-dc76cb56-5856-4101-957f-4775b0f5561c.png)

**Comment by LambdAurora** [comment] 2022-02-18 12:31
This is a duplicate of #9.

**Closed as completed by LambdAurora** 2022-02-18 12:31 UTC
Labels: duplicate
